#!/bin/bash
#--------------------------------------------------------------------------
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments. The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#--------------------------------------------------------------------------
# To enable this hook, rename this file to "pre-commit".
#--------------------------------------------------------------------------
# This pre-commit hook validates your files for ESLint and Stylelint issues
# If any issues are found, the commit you made will be rejected.
#--------------------------------------------------------------------------

set -e

if grep -r "eslint-disable" src/; 
then
    echo "Your code disabled some eslint rules please enable the rules and fix the issues"
    exit 1
fi

npx eslint "src/**/*.{js,jsx,ts,tsx}" --max-warnings 0 --no-error-on-unmatched-pattern
eslint_exit_code=$?

if [ $eslint_exit_code -ne 0 ]
then
  echo "Your code has ESLint errors. Resolve them before committing the code."
  exit 1
fi

npx stylelint src/**/*.css src/**/*.scss --allow-empty-input
stylelint_exit_code=$?

if [ $stylelint_exit_code -ne 0 ]
then
  echo "Your code has Stylelint errors. Resolve them before committing the code."
  exit 1
fi

exit 0
